### ISSUE TITLE
Server auto-update

### ISSUE THREAD

**Issue by sollevix67** [mroote/factorio-server-manager#177] opened 2020-08-10 23:55 UTC
Hello,

For those who have forked this repository, have you added the possibility to update the factorio binary automatically before starting the server  ?

Or by clicking on a button ?

Thanks.

**Comment by knoxfighter** [comment] 2020-08-11 00:44
Not yet, no :(
An autoupdate with the current layout is hard to implement and will take a while. Im currently working on other factorio related projects, but when i come back to this server manager, its high on the list to implement. (After implementing the new UI and fixing all the broken stuff)

Duplicate of #10

**Comment by knoxfighter** [comment] 2020-08-18 17:18
Implemented with #179

**Closed by knoxfighter** 2020-08-18 17:18 UTC
